import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src: [
    {
      path: "../../public/fonts/FiraCode-VariableFont_wght.ttf",
      weight: '300',
      style: 'normal',
    },
    {
      path: "../../public/fonts/FiraCode-VariableFont_wght.ttf",
      weight: '400',
      style: 'normal',
    },
    {
      path: "../../public/fonts/FiraCode-VariableFont_wght.ttf",
      weight: '500',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: "Blasco Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
