export const projects = [
  {
    title: "Project 1",
    subtitle: " // This is a subtitle",
    description: "This is a description",
    icon: "/icons/react-project-icon.svg",
    image: "/images/react-project.png",
    link: "#asd",
    stack: "react",
  },
  {
    title: "Project 2",
    subtitle: " // This is a subtitle",
    description: "This is a description",
    icon: "/icons/react-project-icon.svg",
    image: "/images/react-project.png",
    link: "#",
    stack: "react",
  },
  {
    title: "Project 3",
    subtitle: " // This is a subtitle",
    description: "This is a description",
    icon: "/icons/react-project-icon.svg",
    image: "/images/react-project.png",
    link: "#",
    stack: "react",
  },
  {
    title: "Project 4",
    subtitle: " // This is a subtitle",
    description: "This is a description",
    icon: "/icons/react-project-icon.svg",
    image: "/images/react-project.png",
    link: "#",
    stack: "react",
  },
  {
    title: "Project 5",
    subtitle: " // This is a subtitle",
    description: "This is a description",
    icon: "/icons/react-project-icon.svg",
    image: "/images/react-project.png",
    link: "#",
    stack: "react",
  },
  {
    title: "Project 6",
    subtitle: " // This is a subtitle",
    description: "This is a description",
    icon: "/icons/react-project-icon.svg",
    image: "/images/react-project.png",
    link: "#",
    stack: "react",
  },
];
